[package]
name = "ble-receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["bluetoothd"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros", "io-util", "io-std"] }
env_logger = "0.11.8"