[package]
name = "ble-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.4", features = ["bluetoothd"] }
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "time"] }
futures = "0.3"
env_logger = "0.11"
log = "0.4"
